name: "Beta Project Issue Adder + Labeler"
branding:
  color: "purple"
  icon: "file-plus"
description: "When an issue is created on your repo, this action automatically labels it and adds it to a specified beta project."
inputs:
  actions:
    description: "A JSON object containing the data for which labels create cards on which project board."
    required: true
    default: '{"data": [
      {
      "label": "bug",
      "project": "Bug Tracker Project",
      "project-type": "repo"
      "column": "To-Fix",
      "repo": "bug-tracker-repo"
      },
      {
      "label": "wontfix",
      "project": "Some Organization-wide Project",
      "project-type": "org"
      "column": "Icebox",
      "org": "super-important-org"
      }
      ]}'
  github-token:
    description: "Your GitHub access token"
    required: true
    default: ${{github.token}}
runs:
  using: "node16"
  main: "index.js"
